logging:
  level:
    ROOT: WARN
    com.crypto.sick.trade: INFO
    com.bybit.api.client.websocket.impl: OFF

server:
  port : 8081

schedulers:
  tradeInterval: 15 #seconds
  rsiLazyUpdateInterval: 35
  rsiForceUpdateInterval: 7
  webSocketUpdateInterval: 60
  walletUpdateInterval: 60
  statusVerifierInterval: 120

# test changes 7

sick-trader.config:
  amazon.dynamodb:
    region: "localhost"
    endpoint: http://localhost:8000/
  amazon.aws.accesskey: release14
  amazon.aws.secretkey: release
  supportedPercentile:
    - PERCENTILE85
    - PERCENTILE80
    - PERCENTILE75
  supportedIntervals:
    - INTERVAL_30m
  disableOnStopLoss: true
  users:
    - name: jubakaDemo # Low stop loss values & high take profit values
      status: ENABLED
      trade:
        linear:
          LTCUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_1
              buyAmount: 200 # $
              leverage: 4
              flows:
                MAIN_FLOW:
                  syncStrategies: true
                  stopLoss: 1.8  # %
                  takeProfit: 5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.6  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 70
                      lowCriticalValue: 30
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.6
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 80
                      lowCriticalValue: 20
                TAKE_PROFIT_FLOW:
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 64
                      lowCriticalValue: 36
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 73
                      lowCriticalValue: 27
                HEDGE_FLOW:
                  syncStrategies: false
                  stopLoss: 0.6  # %
                  takeProfit: 1.2 # %
                  strategies:
                    HEDGE_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.1  # %
          XRPUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          ETHUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          BTCUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          SOLUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          TRXUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          BNBUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          ADAUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          AVAXUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_2
              buyAmount: 200 # $
              leverage: 4
              flows:
                MAIN_FLOW:
                  syncStrategies: true
                  stopLoss: 2.2  # %
                  takeProfit: 5.5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.7  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 72
                      lowCriticalValue: 28
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.7
                      indicatorOffset: 4
                      stopLossTimeout: 360
                      highCriticalValue: 81.5
                      lowCriticalValue: 18.5
                TAKE_PROFIT_FLOW:
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 64
                      lowCriticalValue: 36
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 73
                      lowCriticalValue: 27
                HEDGE_FLOW:
                  syncStrategies: false
                  stopLoss: 0.6  # %
                  takeProfit: 1.2 # %
                  strategies:
                    HEDGE_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.1  # %
          SUIUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          AAVEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          HBARUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          DOGEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          VIRTUALUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          ENAUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
#    - name: jubaka-obiTwo-demo  # High stop loss values & high take profit values
#      status: ENABLED
#      trade:
#        linear:
#          LTCUSDT:
#            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#              buyAmount: 200 # $
#              leverage: 4
#              flows:
#                MAIN_FLOW:
#                  syncStrategies: true
#                  stopLoss: 7  # %
#                  takeProfit: 5 # %
#                  strategies:
#                    RSI_STRATEGY:
#                      type: RSI_STRATEGY
#                      priceOffset: 0.6  # %
#                      indicatorOffset: 3
#                      stopLossTimeout: 360
#                      highCriticalValue: 70
#                      lowCriticalValue: 30
#                    MFI_STRATEGY:
#                      type: MFI_STRATEGY
#                      priceOffset: 0.6
#                      indicatorOffset: 3
#                      stopLossTimeout: 360
#                      highCriticalValue: 80
#                      lowCriticalValue: 20
#                TAKE_PROFIT_FLOW:
#                  syncStrategies: false
#                  strategies:
#                    RSI_STRATEGY:
#                      type: RSI_STRATEGY
#                      priceOffset: 0.3  # %
#                      indicatorOffset: 2
#                      stopLossTimeout: 360
#                      highCriticalValue: 64
#                      lowCriticalValue: 36
#                    MFI_STRATEGY:
#                      type: MFI_STRATEGY
#                      priceOffset: 0.3  # %
#                      indicatorOffset: 3
#                      stopLossTimeout: 360
#                      highCriticalValue: 73
#                      lowCriticalValue: 27
#          XRPUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          ETHUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          BTCUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          SOLUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          TRXUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          BNBUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          ADAUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_OBITWO
#          AVAXUSDT:
#            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#              buyAmount: 200 # $
#              leverage: 4
#              flows:
#                MAIN_FLOW:
#                  syncStrategies: true
#                  stopLoss: 9  # %
#                  takeProfit: 6.5 # %
#                  strategies:
#                    RSI_STRATEGY:
#                      type: RSI_STRATEGY
#                      priceOffset: 0.7  # %
#                      indicatorOffset: 3
#                      stopLossTimeout: 360
#                      highCriticalValue: 72
#                      lowCriticalValue: 28
#                    MFI_STRATEGY:
#                      type: MFI_STRATEGY
#                      priceOffset: 0.7
#                      indicatorOffset: 4
#                      stopLossTimeout: 360
#                      highCriticalValue: 81.5
#                      lowCriticalValue: 18.5
#                TAKE_PROFIT_FLOW:
#                  syncStrategies: false
#                  strategies:
#                    RSI_STRATEGY:
#                      type: RSI_STRATEGY
#                      priceOffset: 0.3  # %
#                      indicatorOffset: 2
#                      stopLossTimeout: 360
#                      highCriticalValue: 64
#                      lowCriticalValue: 36
#                    MFI_STRATEGY:
#                      type: MFI_STRATEGY
#                      priceOffset: 0.3  # %
#                      indicatorOffset: 3
#                      stopLossTimeout: 360
#                      highCriticalValue: 73
#                      lowCriticalValue: 27
#          SUIUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#          AAVEUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#          HBARUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#          DOGEUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#          VIRTUALUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO
#          ENAUSDT:
#            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_OBITWO

  debug-mode: false