logging:
  level:
    ROOT: WARN
    com.crypto.sick.trade: INFO

server:
  port : 8081

schedulers:
  tradeInterval: 2 #seconds
  rsiLazyUpdateInterval: 30
  rsiForceUpdateInterval: 2
  webSocketUpdateInterval: 60
  walletUpdateInterval: 60

# test changes 7

sick-trader.config:
  amazon.dynamodb:
    region: "localhost"
    endpoint: http://localhost:8000/
  amazon.aws.accesskey: release14
  amazon.aws.secretkey: release
  supportedPercentile:
    - PERCENTILE85
    - PERCENTILE80
    - PERCENTILE75
  supportedIntervals:
    - INTERVAL_30m
  disableOnStopLoss: true
  users:
    - name: jubakaDemo
      enabled: true
      trade:
        linear:
          #          COOKIEUSDT:
          #            INTERVAL_30m:
          #              buyAmount: 7 # $
          #              leverage: 1
          #              flows:
          #                CHAIN_FLOW: &30M_CHAIN_FLOW_TEMPLATE
          #                  syncStrategies: true
          #                  stopLoss: 1.9  # %
          #                  takeProfit: 1.3 # %
          #                  strategies:
          #                    CHAIN_STRATEGY:
          #                      type: CHAIN_STRATEGY
          #                      priceOffset: 0.1  # %
          LTCUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_1
              buyAmount: 200 # $
              leverage: 4
              flows: &30M_FLOWS_TEMPLATE_VOLATILE_1
                MAIN_FLOW: &30M_MAIN_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: true
                  stopLoss: 2.8  # %
                  takeProfit: 4.5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.6  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 70
                      lowCriticalValue: 30
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.6
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 80
                      lowCriticalValue: 20
                TAKE_PROFIT_FLOW: &30M_TAKE_PROFIT_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 58
                      lowCriticalValue: 42
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 69
                      lowCriticalValue: 31
                OVERTAKE_FLOW: &30M_OVERTAKE_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: false
                  strategies:
                    OVERTAKE_STRATEGY:
                      type: OVERTAKE_STRATEGY
                      priceOffset: 1  # %
          XRPUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          SOLUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          TRXUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          BNBUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          SUIUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          ADAUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1
          AVAXUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_2
              buyAmount: 200 # $
              leverage: 4
              flows: &30M_FLOWS_TEMPLATE_VOLATILE_2
                MAIN_FLOW:
                  syncStrategies: true
                  stopLoss: 3.5  # %
                  takeProfit: 5.5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.7  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 71
                      lowCriticalValue: 29
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.7
                      indicatorOffset: 4
                      stopLossTimeout: 360
                      highCriticalValue: 81.5
                      lowCriticalValue: 18.5
                TAKE_PROFIT_FLOW: &30M_TAKE_PROFIT_FLOW_TEMPLATE_VOLATILE_2
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 58
                      lowCriticalValue: 42
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 69
                      lowCriticalValue: 31
                OVERTAKE_FLOW:
                  syncStrategies: false
                  strategies:
                    OVERTAKE_STRATEGY:
                      type: OVERTAKE_STRATEGY
                      priceOffset: 1.4  # %
          AAVEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          HBARUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          DOGEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          VIRTUALUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
          UNIUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2
    - name: jubaka
      enabled: true
      trade:
        linear:
          LTCUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
              buyAmount: 60 # $
              leverage: 5
              flows: &30M_FLOWS_TEMPLATE_VOLATILE_1
                MAIN_FLOW: &30M_MAIN_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: true
                  stopLoss: 2.8  # %
                  takeProfit: 4.5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.6  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 70
                      lowCriticalValue: 30
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.6
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 80
                      lowCriticalValue: 20
                TAKE_PROFIT_FLOW: &30M_TAKE_PROFIT_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 58
                      lowCriticalValue: 42
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 69
                      lowCriticalValue: 31
                OVERTAKE_FLOW: &30M_OVERTAKE_FLOW_TEMPLATE_VOLATILE_1
                  syncStrategies: false
                  strategies:
                    OVERTAKE_STRATEGY:
                      type: OVERTAKE_STRATEGY
                      priceOffset: 1  # %
          XRPUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          SOLUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          TRXUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          BNBUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          SUIUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          ADAUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_1_PROD
          AVAXUSDT:
            INTERVAL_30m: &30M_INTERVAL_TEMPLATE_VOLATILE_2_PROD
              buyAmount: 60 # $
              leverage: 5
              flows: &30M_FLOWS_TEMPLATE_VOLATILE_2
                MAIN_FLOW:
                  syncStrategies: true
                  stopLoss: 3.5  # %
                  takeProfit: 5.5 # %
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.7  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 71
                      lowCriticalValue: 29
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.7
                      indicatorOffset: 4
                      stopLossTimeout: 360
                      highCriticalValue: 81.5
                      lowCriticalValue: 18.5
                TAKE_PROFIT_FLOW: &30M_TAKE_PROFIT_FLOW_TEMPLATE_VOLATILE_2
                  syncStrategies: false
                  strategies:
                    RSI_STRATEGY:
                      type: RSI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 2
                      stopLossTimeout: 360
                      highCriticalValue: 58
                      lowCriticalValue: 42
                    MFI_STRATEGY:
                      type: MFI_STRATEGY
                      priceOffset: 0.3  # %
                      indicatorOffset: 3
                      stopLossTimeout: 360
                      highCriticalValue: 69
                      lowCriticalValue: 31
                OVERTAKE_FLOW:
                  syncStrategies: false
                  strategies:
                    OVERTAKE_STRATEGY:
                      type: OVERTAKE_STRATEGY
                      priceOffset: 1.4  # %
          AAVEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_PROD
          HBARUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_PROD
          DOGEUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_PROD
          VIRTUALUSDT:
            INTERVAL_30m: *30M_INTERVAL_TEMPLATE_VOLATILE_2_PROD

  debug-mode: false