sick-trader.config.credentials:
  bybit:
    jubaka:
      key: "bybit-key"
      secret: "bybit-secret"
  taapiUrl: "https://api.taapi.io/"
  taapiSecret: "taapi-secret"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      feign: true
