package com.crypto.sick.trade.dto.enums;

public enum CoinEnum {
    USDT("USDT"),
    BTC("BTC"),
    LTC("LTC"),
    ETH("ETH"),
    EOS("EOS"),
    XRP("XRP"),
    BCH("BCH"),
    TRX("TRX"),
    ADA("ADA"),
    XLM("XLM"),
    LINK("LINK"),
    XTZ("XTZ"),
    ATOM("ATOM"),
    DASH("DASH"),
    ZEC("ZEC"),
    ETC("ETC"),
    VET("VET"),
    QTUM("QTUM"),
    IOTA("IOTA"),
    NEO("NEO"),
    ALGO("ALGO"),
    ZRX("ZRX"),
    COMP("COMP"),
    OMG("OMG"),
    DOGE("DOGE"),
    SUSHI("SUSHI"),
    UNI("UNI"),
    YFI("YFI"),
    AAVE("AAVE"),
    MKR("MKR"),
    SNX("SNX"),
    CRV("CRV"),
    REN("REN"),
    BAL("BAL"),
    KNC("KNC"),
    BAND("BAND"),
    LRC("LRC"),
    UMA("UMA"),
    MANA("MANA"),
    CVC("CVC"),
    STORJ("STORJ"),
    OXT("OXT"),
    BNT("BNT"),
    ENJ("ENJ"),
    GRT("GRT"),
    SAND("SAND"),
    MATIC("MATIC"),
    SKL("SKL"),
    SLP("SLP"),
    SOL("SOL"),
    MNT("MNT"),
    PEPE("PEPE"),
    TON("TON"),
    NOT("NOT"),
    VIRTUAL("VIRTUAL"),
    ELX("ELX"),
    TRUMP("TRUMP"),
    APEX("APEX"),
    HBAR("HBAR"),
    BNB("BNB"),
    DRIFT("DRIFT"),
    ROAM("ROAM"),
    GALA("GALA"),
    SCA("SCA"),
    OBT("OBT"),
    SHARP("SHARP"),
    SQD("SQD"),
    NS("NS"),
    DGB("DGB"),
    KAIA("KAIA"),
    SAFE("SAFE"),
    XDC("XDC"),
    SUI("SUI"),
    AVAX("AVAX"),
    TRB("TRB"),
    CATI("CATI"),
    GUN("GUN"),
    XMR("XMR"),
    COOKIE("COOKIE"),
    KAVA("KAVA"),
    LAUNCHCOIN("LAUNCHCOIN"),
    AWE("AWE"),
    ZORA("ZORA"),
    DARK("DARK"),
    BANK("BANK"),
    HAEDAL("HAEDAL"),
    SYRUP("SYRUP");


    private final String coin;

    CoinEnum(String coin) {
        this.coin = coin;
    }

    public String getCoin() {
        return coin;
    }
}
